- name: NIST remediations
  hosts: localhost
  tasks:
    - name: edit the target of remediation to local host
      ansible.builtin.lineinfile:
        path: NIST_800-171_remediations.yml
        regexp: '^- hosts:'
        insertafter: '^#- hosts:'
        line: "- hosts: localhost"
        
- name: Include NIST 800-171 remediation tasks and generate a final results status
  tasks:
    - include: NIST_800-171_remediations.yml
    - name: generate new results file for NIST remediations
      command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --results final_NIST_800-171_scan_results.xml --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
      ignore_errors: true
