- name: edit NIST remediations to run on localhost
  hosts: localhost
  tasks:
    - name: edit the target of remediation to local host
      ansible.builtin.lineinfile:
        path: NIST_800-171_remediations.yml
        regexp: '^- hosts:'
        insertafter: '^#- hosts:'
        line: "- hosts: localhost"
  
- name: run NIST remediations
- import_playbook: NIST_800-171_remediations.yml

- name: Generate a final results status for NIST compliance
  hosts: localhost
  tasks:
    - name: generate new results file for NIST remediations
      command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --results final_NIST_800-171_scan_results.xml --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
      ignore_errors: true
