---
- name: install required packages and genereate NIST 800-171 fix
  hosts: localhost
  tasks:
  
    - name: ensure required packages are installed
      yum:
        name:
          - scap-security-guide
          - rhel-system-roles
    
    - name: install required ansible collections
      command: ansible-galaxy collection install community.general
      command: ansible-galaxy collection install ansible.posix
      
    - name: scan system for NIST 800-171 compliance and generate results file
      command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --results initial_NIST_800-171_scan_results.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
    
    - name: generate an ansible fix for NIST 800-171 compliance based on results in initial_NIST_800-171_scan_results.xml
      command: oscap xccdf generate fix --fix-type ansible --profile xccdf_org.ssgproject.content_profile_cui --output NIST_800-171_remediations.yml initial_NIST_800-171_scan_results.xml
      
- name: format and mount disk
  hosts: localhost
  vars:
    storage_volumes:
      - name: {{vol_name}}
        type: disk
        disks: {{vol_disk}}
        fs_type: xfs
        mount_point: {{vol_mount_point}}
    
  roles: 
    - rhel-system-roles.storage:
            

    
