---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  tasks:
    ###install neccessary content for ansible to work###
    - name: run initial set up
      include_tasks: initial_prep.yml 
    ###verify that variables have been set by the user###
    - name: Check that lvm_size variable is defined and not empty
      ansible.builtin.assert:
        that:
          - lvm_size is defined
          - lvm_size | length > 0
        fail_msg: "You must define 'lvm_size' (e.g. 10g)."
        success_msg: "lvm_size is defined and valid."
    - name: Check that vol_disks variable is defined and contains at least one disk
      ansible.builtin.assert:
        that:
          - vol_disks is defined
          - vol_disks | length > 0
        fail_msg: "You must define 'vol_disks' with at least one disk (e.g. ['/dev/sdb'])."
        success_msg: "vol_disks is defined and has at least one disk."
    - name: Check that veeam_user_password variable is defined and not empty
      ansible.builtin.assert:
        that:
          - veeam_user_password is defined
          - veeam_user_password | length > 0
        fail_msg: "You must define 'veeam_user_password'."
        success_msg: "veeam_user_password is defined and valid."

    
    ###continue if ok###

    - name: create user
      include_tasks: create_user.yml
    - name: create disk
      include_tasks: create_disk.yml
    - name: set permissions
      include_tasks: permissions.yml

  
#- name: edit NIST remediations so that they will run on localhost
#  hosts: localhost
#  tasks:
#    - name: edit the target of remediation to local host
#      ansible.builtin.lineinfile:
#        path: NIST_800-171_remediations.yml
#        regexp: '^- hosts:'
#        insertafter: '^#- hosts:'
#        line: "- hosts: localhost"    
