---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  tasks:

    ###verify variables are set and install neccessary content###
    - name: run initial set up
      include_tasks: tasks/initial_prep.yml 
    
    ###continue if ok###
    - name: Format and mount disk via storage role
      ansible.builtin.include_role:
        name: rhel-system-roles.storage
      vars:
        storage_pools:
          - name: "{{ lvm_name }}"
            type: lvm
            disks: "{{ vol_disks }}"
            volumes:
              - name: "{{ vol_name }}"
                size: "{{ lvm_size }}"
                fs_type: xfs
                mount_point: "{{ vol_mount_point }}"

    - name: create user
      include_tasks: tasks/create_user.yml
    - name: set permissions
      include_tasks: tasks/permissions.yml

  
#- name: edit NIST remediations so that they will run on localhost
#  hosts: localhost
#  tasks:
#    - name: edit the target of remediation to local host
#      ansible.builtin.lineinfile:
#        path: NIST_800-171_remediations.yml
#        regexp: '^- hosts:'
#        insertafter: '^#- hosts:'
#        line: "- hosts: localhost"    
