---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  pre_tasks:

    ###verify that variables have been set by the user###
    - name: Check that lvm_size variable is defined and not empty
      ansible.builtin.assert:
        that:
          - lvm_size is defined
          - lvm_size is not none
        fail_msg: "You must define 'lvm_size' (e.g. 10g)."
        success_msg: "lvm_size is defined and valid."
    - name: Check that vol_disks variable is defined and contains at least one disk
      ansible.builtin.assert:
        that:
          - vol_disks is defined
          - vol_disks is not none
        fail_msg: "You must define 'vol_disks' with at least one disk (e.g. ['/dev/sdb'])."
        success_msg: "vol_disks is defined and has at least one disk."
    - name: Check that veeam_user_password variable is defined and not empty
      ansible.builtin.assert:
        that:
          - veeam_user_password is defined
          - veeam_user_password is not none
        fail_msg: "You must define 'veeam_user_password'."
        success_msg: "veeam_user_password is defined and valid."

    - name: run initial set up
      include_tasks: initial_prep.yml 
    ###continue if ok###
    ###install neccessary content for ansible to work###
  roles:
    - role: rhel-system-roles.storage     
      vars:
        storage_pools:
        - name: "{{lvm_name}}"
          type: lvm
          disks: "{{vol_disk}}"
          volumes:
            - name: "{{vol_name}}"
              size: "{{lvm_size}}"
              mount_point: "{{vol_mount_point}}"
              fs_type: xfs       
  tasks:
    - name: create user
      include_tasks: create_user.yml
    - name: set permissions
      include_tasks: permissions.yml

  
#- name: edit NIST remediations so that they will run on localhost
#  hosts: localhost
#  tasks:
#    - name: edit the target of remediation to local host
#      ansible.builtin.lineinfile:
#        path: NIST_800-171_remediations.yml
#        regexp: '^- hosts:'
#        insertafter: '^#- hosts:'
#        line: "- hosts: localhost"    
