---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  tasks:
    - name: run initial set up
      include_tasks: initial_prep.yml 
    - name: create user
      include_tasks: create_user.yml
      
- name: format and mount disk
  hosts: localhost
  vars_files: 
    - vars.yml
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
    storage_volumes:
      - name: "{{vol_name}}"
        type: disk
        disks: "{{vol_disk}}"
        fs_type: xfs
        mount_point: "{{vol_mount_point}}"    
  roles: 
    - rhel-system-roles.storage

- name: include task
  hosts: localhost
  include_tasks: NIST_800-171_remediations.yml
    
