---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars:
    include_vars: vars.yml

  tasks:
    - name: run initial set up
      include_tasks: initial_prep.yml 
    - name: create disk
      include_tasks: create_disk.yml
    - name: create user
      include_tasks: create_user.yml


- name: include task
  hosts: localhost
  tasks:
    - name: include tasks
      include_tasks: NIST_800-171_remediations.yml
    
