---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars:
    include_vars: vars.yml

  include_playbook: initial_prep.yml
  include_playbook: create_disk.yml
  include_playbook: create_user.yml
  include_playbook: NIST_800-171_remediations.yml
    
