---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars:
    include_vars: vars.yml
  tasks:
    import_playbook:
      - initial_prep.yml
      - create_disk.yml
      - create_user.yml
    include_playbook:
      - NIST_800-171_remediations.yml
    
