---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  tasks:
    ###verify variables are set and install neccessary dependencies###
    - name: run initial set up
      include_tasks: tasks/initial_prep.yml 

    - name: run security scan for compliance with DISA STIG
      include_tasks: tasks/security_scan.yml

    - block:   
      - name: enable FIPS
        include_tasks: tasks/enable_FIPS.yml
      when: enable_FIPS | default(false) | bool

    - block:
      - name: Format and mount disk via storage role
        ansible.builtin.include_role:
          name: fedora.linux_system_roles.storage
        vars:
          storage_pools:
            - name: "{{ lvm_name }}"
              type: lvm
              disks: "{{ vol_disks }}"
              volumes:
                - name: "{{ vol_name }}"
                  size: "{{ lvm_size }}"
                  fs_type: xfs
                  mount_point: "{{ vol_mount_point }}"
                  mount_options: "nodev,nosuid,noexec,noatime"
      when: configure_storage | default(false) | bool   

    - block:
      - name: create grub users
        include_tasks: tasks/create_grub_user.yml
      when: create_grub | default(false) | bool

    - block:
      - name: set max number of user namespaces to 0
        include_tasks: tasks/user_namespaces.yml
      when: user_namespaces | default(false) | bool

    - block:  
      - name: set NTP security options
        include_tasks: tasks/ntp-security.yml
      when: setup_ntp | default(false) | bool

    - block:
      - name: set up SSSD (LDAP/AD Cert verification)
        include_tasks: tasks/SSSD_setup.yml

    - name: create user
      include_tasks: tasks/create_user.yml

    - name: set permissions
      include_tasks: tasks/permissions.yml

    - name: enable automatic security updates
      include_tasks: tasks/enable_auto_security.yml

    - name: Elevate SELinux context of sudo
      include_tasks: tasks/allow_sudo_selinux.yml


