---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars:
    include_vars: vars.yml

- import_playbook: initial_prep.yml
- import_playbook: create_disk.yml
- import_playbook: create_user.yml
- include_tasks: NIST_800-171_remediations.yml
    
