---
- name: create a Linux Hardened Repository
  hosts: localhost
  vars_files: 
    - vars.yml

  tasks:
    ###verify variables are set and install neccessary dependencies###
    - name: run initial set up
      include_tasks: tasks/initial_prep.yml 
    
    ###continue if ok###
    - name: Format and mount disk via storage role
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.storage
      vars:
        storage_pools:
          - name: "{{ lvm_name }}"
            type: lvm
            disks: "{{ vol_disks }}"
            volumes:
              - name: "{{ vol_name }}"
                size: "{{ lvm_size }}"
                fs_type: xfs
                mount_point: "{{ vol_mount_point }}"

    - name: create user
      include_tasks: tasks/create_user.yml
    - name: set permissions
      include_tasks: tasks/permissions.yml
    - name: enable automatic security updates
      include_tasks: tasks/enable_auto_security.yml
    - name: run security scan for compliance with DISA STIG
      include_tasks: tasks/security_scan.yml

