- block:
    - name: Ensure /etc/grub.d/01_users has the right superuser
      ansible.builtin.lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^\s*set\s+superusers=.*$'
        line: 'set superusers="{{ grub_superuser_name }}"'
        create: yes
        mode: '0755'        # make script executable
        backup: yes
      register: set_super_line

    - name: Ensure export superusers is present (after the set line)
      ansible.builtin.lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^\s*export\s+superusers\s*$'
        line: 'export superusers'
        insertafter: '^\s*set\s+superusers='
        create: yes
      register: export_line

    - name: Ensure password_pbkdf2 line uses the same username
      ansible.builtin.lineinfile:
        path: /etc/grub.d/01_users
        # Match the existing password line that references GRUB2_PASSWORD
        regexp: '^\s*password_pbkdf2\s+\S+\s+\$\{?GRUB2_PASSWORD\}?'
        line: 'password_pbkdf2 {{ grub_superuser_name }} ${GRUB2_PASSWORD}'
        create: yes
      register: pw_line

    - name: Regenerate grub.cfg if 01_users changed
      ansible.builtin.command:
        cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: set_super_line.changed or export_line.changed or pw_line.changed

