---
# Ensure pam_securetty is enforced for console logins (blocks root on TTYs)
- name: Check for /etc/pam.d/login (console login PAM stack)
  ansible.builtin.stat:
    path: /etc/pam.d/login
  register: _pam_login

- name: Enforce pam_securetty in console login stack
  ansible.builtin.lineinfile:
    path: /etc/pam.d/login
    regexp: '^\s*auth\s+required\s+pam_securetty\.so(\s|$)'
    line: 'auth       required    pam_securetty.so'
    insertafter: BOF
    backup: true
  when: _pam_login.stat.exists

# Empty /etc/securetty so root is allowed on zero TTYs
- name: Backup existing /etc/securetty (once)
  ansible.builtin.copy:
    src: /etc/securetty
    dest: /root/securetty.backup
    remote_src: true
    force: false
  when: ansible_facts['os_family'] is defined and
        (ansible_facts['os_family'] | lower) in ['redhat', 'debian', 'suse'] and
        (lookup('ansible.builtin.fileglob', '/etc/securetty', errors='ignore') | length) > 0

- name: Disable root console logins by emptying /etc/securetty
  ansible.builtin.copy:
    dest: /etc/securetty
    content: ""          # empty file → no secure TTYs
    owner: root
    group: root
    mode: "0600"
