---
- name: Check that lvm_size variable is defined and not empty
  ansible.builtin.assert:
    that:
      - lvm_size is defined
      - lvm_size is not none
    fail_msg: "You must define 'lvm_size' (e.g. 10g)."
    success_msg: "lvm_size is defined and valid."

- name: Check that vol_disks variable is defined and contains at least one disk
  ansible.builtin.assert:
    that:
      - vol_disks is defined
      - vol_disks is not none
    fail_msg: "You must define 'vol_disks' with at least one disk (e.g. ['/dev/sdb'])."
    success_msg: "vol_disks is defined and has at least one disk."

- name: Check that veeam_user_password variable is defined and not empty
  ansible.builtin.assert:
    that:
      - veeam_user_password is defined
      - veeam_user_password is not none
    fail_msg: "You must define 'veeam_user_password'."
    success_msg: "veeam_user_password is defined and valid."

- name: ensure required packages are installed
  yum:
    name:
      - scap-security-guide

- name: install community.general ansible collection
  command: ansible-galaxy collection install -r requirements.yml


# - name: scan system for NIST 800-171 compliance and generate results file
#   command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --results initial_NIST_800-171_scan_results.xml --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
#   ignore_errors: true

# - name: generate an ansible fix for NIST 800-171 compliance based on results in initial_NIST_800-171_scan_results.xml
#   command: "oscap xccdf generate fix --fix-type ansible --profile xccdf_org.ssgproject.content_profile_cui --output NIST_800-171_remediations.yml initial_NIST_800-171_scan_results.xml"

# - name: create compliance report
#   command: "oscap xccdf generate report initial_NIST_800-171_scan_results.xml > initial_NIST_800-171_compliance_report.html"



