---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  tags:
    - CCE-87232-5
    - DISA-STIG-RHEL-09-252050
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - postfix_prevent_unrestricted_relay
    - restrict_strategy

- name: Prevent Unrestricted Mail Relaying
  block:
    - name: Check for duplicate smtpd_client_restrictions lines
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        create: true
        regexp: '(?i)^\s*smtpd_client_restrictions\s*=\s*.*$'
        state: absent
      check_mode: true
      changed_when: false
      register: postfix_dupes

    - name: Deduplicate smtpd_client_restrictions entries
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        create: true
        regexp: '(?i)^\s*smtpd_client_restrictions\s*=\s*.*$'
        state: absent
      when: postfix_dupes.found is defined and postfix_dupes.found > 1

    - name: Set smtpd_client_restrictions to permit_mynetworks,reject
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        create: true
        regexp: '(?i)^\s*smtpd_client_restrictions\s*=\s*.*$'
        line: 'smtpd_client_restrictions = permit_mynetworks,reject'
        state: present
  when:
    - "'kernel' in ansible_facts.packages"
    - "'postfix' in ansible_facts.packages"
  tags:
    - CCE-87232-5
    - DISA-STIG-RHEL-09-252050
    - low_complexity
    - low_disruption
    - medium_severity
    - no_reboot_needed
    - postfix_prevent_unrestricted_relay
    - restrict_strategy
