---


- name: Normalize MACs line order in crypto-policy back-ends
  ansible.builtin.replace:
    path: /etc/crypto-policies/back-ends/openssh.config
    regexp: '^[ \t]*MACs[ \t]+.*$'
    replace: "MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512"
    backup: true

# 2) If there was no MACs line, ensure it exists once at EOF
- name: Ensure MACs line exists once with exact STIG order
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/openssh.config
    regexp: '^[ \t]*MACs[ \t]+'
    line: "MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512"
    insertafter: EOF
    create: true
    backup: true


- name: Normalize MACs line order in crypto-policy back-ends
  ansible.builtin.replace:
    path: /etc/crypto-policies/back-ends/opensshserver.config
    regexp: '^[ \t]*MACs[ \t]+.*$'
    replace: "MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512"
    backup: true

# 2) If there was no MACs line, ensure it exists once at EOF
- name: Ensure MACs line exists once with exact STIG order
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensshserver.config
    regexp: '^[ \t]*MACs[ \t]+'
    line: "MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512"
    insertafter: EOF
    create: true
    backup: true