---

- name: Derive header and domain list
  ansible.builtin.set_fact:
    _certmap_header_domain: "{{ certmap_domain_id | default((certmap_search_domains | default([])) | first) }}"
    _certmap_domain_list: "{{ certmap_search_domains | default([certmap_domain_id]) }}"

- name: Fail if no domain provided
  ansible.builtin.fail:
    msg: "Provide certmap_domain_id OR a non-empty certmap_search_domains list."
  when: _certmap_header_domain is not defined or (_certmap_header_domain | length) == 0

- name: Ensure /etc/sssd/sssd.conf exists with correct perms
  ansible.builtin.file:
    path: /etc/sssd/sssd.conf
    state: touch
    owner: root
    group: root
    mode: '0600'

- name: Insert certmap block into /etc/sssd/sssd.conf (STIG-visible)
  ansible.builtin.blockinfile:
    path: /etc/sssd/sssd.conf
    marker: "# {mark} ANSIBLE SSSD CERTMAP {{ certmap_rule_name }}"
    create: yes
    owner: root
    group: root
    mode: '0600'
    block: |
      [certmap/{{ _certmap_header_domain }}/{{ certmap_rule_name }}]
      matchrule = {{ certmap_matchrule }}
      maprule  = {{ certmap_maprule }}
      domains  = {{ _certmap_domain_list | join(',') }}